site_name: RAS Solution
site_url: https://workshop.thyintresources.com/ras-solution/
dev_addr: '127.0.0.1:8005'
theme:
  name: material
  
  font:
    text: Manrope
    code: Manrope
  
  logo: img/Delinea.svg
  
  favicon: img/favicon.ico
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    - search.highlight

plugins:
  - search
  - with-pdf:
      author: Delinea Technical Enablement
      cover_logo: images/secretserver.jpg
      cover_title: RAS Solution
      cover_subtitle: VPN Less access to Data Centers
      copyright: Delinea
      debug_html: false
      enabled_if_env: ENABLE_PDF_EXPORT
extra:
  generator: false

nav:
  - Home: index.md
  - Logging into Platform 1.0: mod1/mod1.md
  - Deploy the Cloud Connector: mod2/mod2.md
  - Integrating Secret Server: mod3/mod3.md
  - Configure Cloud Tenant: mod4/mod4.md
  - Configure for test case: mod5/mod5.md
  - Test configuration: mod6/mod6.md
  - Conclusion: mod7/mod7.md



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences